version: '3.8'
services:
  klubiq-dashboard:
    container_name: klubiq-dashboard
    build:
      context: .
      tags:
        - 'klubiq-dashboard'
      args:
        - APP=klubiq-dashboard
      target: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    image: vadeyemi/klubiq-api:latest
#     networks:
#       - dockernet
# networks:
#   dockernet:
#     external: true
