name: Run Database Migration
on:
  push:
    branches:
      - prod
    paths:
      - 'klubiq-db/**'
      - '.github/workflows/run-migrations-prod.yaml'
env:
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  SYNCHRONIZE_DB: ${{ secrets.SYNCHRONIZE_DB }}
  NODE_ENV: ${{ secrets.ENV }}

jobs:
  migration:
    runs-on: ubuntu-latest
    environment: ${{github.env}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: klubiq-db
      - name: Build prject
        run: |
          cd klubiq-db
          npm install
          npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            klubiq-db/build/
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: artifacts/build/
      - name: copy and run migration via ssh
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.LIGHTSAIL_SSH_CERT }}
          SOURCE: 'artifacts/'
          EXCLUDE: '/node_modules/, node_modules, /node_modules'
          TARGET: ${{ vars.DB_TARGET_DIR }}
          SCRIPT_BEFORE: |
            sudo chown $USER ${{ vars.DB_TARGET_DIR }}
            cd ${{ vars.DB_TARGET_DIR }}
          SCRIPT_AFTER: |
            cd ${{ vars.DB_TARGET_DIR }}      
            export DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            export DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            export DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            export SYNCHRONIZE_DB=${{ secrets.SYNCHRONIZE_DB }}
            export NODE_ENV=${{ secrets.ENV }}
            echo "Running NPM GENERATE MIGRATION"
            npm run generate:migration
            echo "Running NPM MIGRATION"
            npm run migration
